// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package metabase

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The email configuration (if any) for Metabase.
//
// Adding email integration enables users to set alerts and system notifications.
//
// https://www.metabase.com/docs/latest/administration-guide/02-setting-up-email.html
type EmailConfig struct {
	Host     *string  `pulumi:"host"`
	Password *string  `pulumi:"password"`
	Port     *float64 `pulumi:"port"`
	Security *string  `pulumi:"security"`
	Username *string  `pulumi:"username"`
}

// EmailConfigInput is an input type that accepts EmailConfigArgs and EmailConfigOutput values.
// You can construct a concrete instance of `EmailConfigInput` via:
//
//          EmailConfigArgs{...}
type EmailConfigInput interface {
	pulumi.Input

	ToEmailConfigOutput() EmailConfigOutput
	ToEmailConfigOutputWithContext(context.Context) EmailConfigOutput
}

// The email configuration (if any) for Metabase.
//
// Adding email integration enables users to set alerts and system notifications.
//
// https://www.metabase.com/docs/latest/administration-guide/02-setting-up-email.html
type EmailConfigArgs struct {
	Host     pulumi.StringPtrInput  `pulumi:"host"`
	Password pulumi.StringPtrInput  `pulumi:"password"`
	Port     pulumi.Float64PtrInput `pulumi:"port"`
	Security pulumi.StringPtrInput  `pulumi:"security"`
	Username pulumi.StringPtrInput  `pulumi:"username"`
}

func (EmailConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EmailConfig)(nil)).Elem()
}

func (i EmailConfigArgs) ToEmailConfigOutput() EmailConfigOutput {
	return i.ToEmailConfigOutputWithContext(context.Background())
}

func (i EmailConfigArgs) ToEmailConfigOutputWithContext(ctx context.Context) EmailConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EmailConfigOutput)
}

func (i EmailConfigArgs) ToEmailConfigPtrOutput() EmailConfigPtrOutput {
	return i.ToEmailConfigPtrOutputWithContext(context.Background())
}

func (i EmailConfigArgs) ToEmailConfigPtrOutputWithContext(ctx context.Context) EmailConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EmailConfigOutput).ToEmailConfigPtrOutputWithContext(ctx)
}

// EmailConfigPtrInput is an input type that accepts EmailConfigArgs, EmailConfigPtr and EmailConfigPtrOutput values.
// You can construct a concrete instance of `EmailConfigPtrInput` via:
//
//          EmailConfigArgs{...}
//
//  or:
//
//          nil
type EmailConfigPtrInput interface {
	pulumi.Input

	ToEmailConfigPtrOutput() EmailConfigPtrOutput
	ToEmailConfigPtrOutputWithContext(context.Context) EmailConfigPtrOutput
}

type emailConfigPtrType EmailConfigArgs

func EmailConfigPtr(v *EmailConfigArgs) EmailConfigPtrInput {
	return (*emailConfigPtrType)(v)
}

func (*emailConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**EmailConfig)(nil)).Elem()
}

func (i *emailConfigPtrType) ToEmailConfigPtrOutput() EmailConfigPtrOutput {
	return i.ToEmailConfigPtrOutputWithContext(context.Background())
}

func (i *emailConfigPtrType) ToEmailConfigPtrOutputWithContext(ctx context.Context) EmailConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EmailConfigPtrOutput)
}

// The email configuration (if any) for Metabase.
//
// Adding email integration enables users to set alerts and system notifications.
//
// https://www.metabase.com/docs/latest/administration-guide/02-setting-up-email.html
type EmailConfigOutput struct{ *pulumi.OutputState }

func (EmailConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EmailConfig)(nil)).Elem()
}

func (o EmailConfigOutput) ToEmailConfigOutput() EmailConfigOutput {
	return o
}

func (o EmailConfigOutput) ToEmailConfigOutputWithContext(ctx context.Context) EmailConfigOutput {
	return o
}

func (o EmailConfigOutput) ToEmailConfigPtrOutput() EmailConfigPtrOutput {
	return o.ToEmailConfigPtrOutputWithContext(context.Background())
}

func (o EmailConfigOutput) ToEmailConfigPtrOutputWithContext(ctx context.Context) EmailConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v EmailConfig) *EmailConfig {
		return &v
	}).(EmailConfigPtrOutput)
}

func (o EmailConfigOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EmailConfig) *string { return v.Host }).(pulumi.StringPtrOutput)
}

func (o EmailConfigOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EmailConfig) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o EmailConfigOutput) Port() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v EmailConfig) *float64 { return v.Port }).(pulumi.Float64PtrOutput)
}

func (o EmailConfigOutput) Security() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EmailConfig) *string { return v.Security }).(pulumi.StringPtrOutput)
}

func (o EmailConfigOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EmailConfig) *string { return v.Username }).(pulumi.StringPtrOutput)
}

type EmailConfigPtrOutput struct{ *pulumi.OutputState }

func (EmailConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EmailConfig)(nil)).Elem()
}

func (o EmailConfigPtrOutput) ToEmailConfigPtrOutput() EmailConfigPtrOutput {
	return o
}

func (o EmailConfigPtrOutput) ToEmailConfigPtrOutputWithContext(ctx context.Context) EmailConfigPtrOutput {
	return o
}

func (o EmailConfigPtrOutput) Elem() EmailConfigOutput {
	return o.ApplyT(func(v *EmailConfig) EmailConfig {
		if v != nil {
			return *v
		}
		var ret EmailConfig
		return ret
	}).(EmailConfigOutput)
}

func (o EmailConfigPtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EmailConfig) *string {
		if v == nil {
			return nil
		}
		return v.Host
	}).(pulumi.StringPtrOutput)
}

func (o EmailConfigPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EmailConfig) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

func (o EmailConfigPtrOutput) Port() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *EmailConfig) *float64 {
		if v == nil {
			return nil
		}
		return v.Port
	}).(pulumi.Float64PtrOutput)
}

func (o EmailConfigPtrOutput) Security() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EmailConfig) *string {
		if v == nil {
			return nil
		}
		return v.Security
	}).(pulumi.StringPtrOutput)
}

func (o EmailConfigPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EmailConfig) *string {
		if v == nil {
			return nil
		}
		return v.Username
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EmailConfigInput)(nil)).Elem(), EmailConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*EmailConfigPtrInput)(nil)).Elem(), EmailConfigArgs{})
	pulumi.RegisterOutputType(EmailConfigOutput{})
	pulumi.RegisterOutputType(EmailConfigPtrOutput{})
}
