# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .metabase import *
from .provider import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "metabase",
  "mod": "index",
  "fqn": "pulumi_metabase",
  "classes": {
   "metabase:index:Metabase": "Metabase"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "metabase",
  "token": "pulumi:providers:metabase",
  "fqn": "pulumi_metabase",
  "class": "Provider"
 }
]
"""
)
