// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

/**
 * The email configuration (if any) for Metabase.
 *
 * Adding email integration enables users to set alerts and system notifications.
 *
 * https://www.metabase.com/docs/latest/administration-guide/02-setting-up-email.html
 */
export interface EmailConfigArgs {
    host?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    port?: pulumi.Input<number>;
    security?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}
