// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

/**
 * Options for setting a custom domain.
 */
export interface CustomDomainArgs {
    domainName?: pulumi.Input<string>;
    hostedZoneName?: pulumi.Input<string>;
}

/**
 * The options for networking.
 */
export interface NetworkingArgs {
    /**
     * The subnets to use for the RDS instance.
     */
    dbSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The subnets to use for the Fargate task.
     */
    ecsSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The subnets to use for the load balancer.
     */
    lbSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
}
