// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Metabase.Inputs
{

    /// <summary>
    /// Options for setting a custom domain.
    /// </summary>
    public sealed class CustomDomainArgs : Pulumi.ResourceArgs
    {
        [Input("domainName")]
        public Input<string>? DomainName { get; set; }

        [Input("hostedZoneName")]
        public Input<string>? HostedZoneName { get; set; }

        public CustomDomainArgs()
        {
        }
    }
}
