// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Metabase.Inputs
{

    /// <summary>
    /// The options for configuring your database.
    /// </summary>
    public sealed class DatabaseArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The database engine version. Updating this argument results in an outage. See the
        /// [Aurora MySQL](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.html)
        /// documentation for your configured engine to determine this value. For example with Aurora MySQL 2,
        /// a potential value for this argument is 5.7.mysql_aurora.2.03.2. The value can contain a partial version
        /// where supported by the API.
        /// </summary>
        [Input("engineVersion")]
        public Input<string>? EngineVersion { get; set; }

        public DatabaseArgs()
        {
            EngineVersion = "5.7.mysql_aurora.2.08.3";
        }
    }
}
