// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Metabase.Inputs
{

    /// <summary>
    /// The options for networking.
    /// </summary>
    public sealed class NetworkingArgs : Pulumi.ResourceArgs
    {
        [Input("dbSubnetIds")]
        private InputList<string>? _dbSubnetIds;

        /// <summary>
        /// The subnets to use for the RDS instance.
        /// </summary>
        public InputList<string> DbSubnetIds
        {
            get => _dbSubnetIds ?? (_dbSubnetIds = new InputList<string>());
            set => _dbSubnetIds = value;
        }

        [Input("ecsSubnetIds")]
        private InputList<string>? _ecsSubnetIds;

        /// <summary>
        /// The subnets to use for the Fargate task.
        /// </summary>
        public InputList<string> EcsSubnetIds
        {
            get => _ecsSubnetIds ?? (_ecsSubnetIds = new InputList<string>());
            set => _ecsSubnetIds = value;
        }

        [Input("lbSubnetIds")]
        private InputList<string>? _lbSubnetIds;

        /// <summary>
        /// The subnets to use for the load balancer.
        /// </summary>
        public InputList<string> LbSubnetIds
        {
            get => _lbSubnetIds ?? (_lbSubnetIds = new InputList<string>());
            set => _lbSubnetIds = value;
        }

        public NetworkingArgs()
        {
        }
    }
}
